<Project>

	<!-- Basic Reference types -->
	<ItemDefinitionGroup>
		<ProjectReference>
			<Scope>Project</Scope>
			<Platform Condition="'$(Platform)' != ''">$(Platform)</Platform>
			<Configuration Condition="'$(Configuration)' != ''">$(Configuration)</Configuration>
			<AdditionalProperties Condition="'$(AdditionalProperties)' != ''">$(AdditionalProperties)</AdditionalProperties>
		</ProjectReference>
		<PackageReference>
			<Scope>Project</Scope>
			<Platform Condition="'$(Platform)' != ''">$(Platform)</Platform>
		</PackageReference>
	</ItemDefinitionGroup>

	<!-- Generic Item types -->
	<ItemDefinitionGroup>
		<Content>
			<ItemType>File</ItemType>
			<FileType>Text</FileType>
		</Content>
		<Resource>
			<ItemType>File</ItemType>
			<FileType>XML</FileType>
		</Resource>
	</ItemDefinitionGroup>

</Project>