<Project>

	<PropertyGroup>
		<ImportProjectExtensionTargets Condition="'$(ImportProjectExtensionTargets)' == ''">true</ImportProjectExtensionTargets>
		<ImportProjectBuildTargets Condition="'$(ImportProjectBuildTargets)' == ''">true</ImportProjectBuildTargets>
	</PropertyGroup>

	<ImportGroup>
		<Import Project="..\Extensions\MSBuild.ProjectExtension.targets" Condition="'$(ImportProjectExtensionTargets)' == 'true'"/>
		<Import Project="..\Extensions\Project.Build.targets" Condition="'$(ImportProjectBuildTargets)' == 'true'"/>
	</ImportGroup>

</Project>