<Project>

	<PropertyGroup>
		<ImportProjectBuildProps Condition="'$(ImportProjectBuildProps)' == ''">true</ImportProjectBuildProps>
		<ImportProjectExtensionProps Condition="'$(ImportProjectExtensionProps)' == ''">true</ImportProjectExtensionProps>
	</PropertyGroup>

	<ImportGroup>
		<Import Project="..\Extensions\Project.Build.props" Condition="'$(ImportProjectBuildProps)' == 'true'"/>
		<Import Project="..\Extensions\MSBuild.ProjectExtension.props" Condition="'$(ImportProjectExtensionProps)' == 'true'"/>
	</ImportGroup>

</Project>