<Project>

	<!--
		The .NET Sdk targets ('Microsoft.NET.Sdk') adds all transitive project references to 'ProjectReference'.
		It does this at build time via a target. If we are not building transitive project references,
		then MSBuild will not add those in the static graph and subsequently will not build them.
	-->
	<PropertyGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true' AND '$(IsGraphBuild)' == 'true'">
		<AddTransitiveProjectReferencesInStaticGraph Condition="'$(AddTransitiveProjectReferencesInStaticGraph)' == '' AND '$(DisableTransitiveProjectReferences)' != 'true'">true</AddTransitiveProjectReferencesInStaticGraph>
	</PropertyGroup>

	<!--
		WPF projects generate a project with a random name at build time and then build the project via the 'IBuildEngine' callbacks.
		Detect WPF, and exclude the generated project from static graph isolation constraint checking.
		Escape the item to avoid eager evaluation of the wildcards.
	-->
	<ItemGroup Condition="'$(IsGraphBuild)' == 'true'">
		<GraphIsolationExemptReference
			Condition="'$(UseWPF)' == 'true' OR @(Page->Count()) != 0 OR @(ApplicationDefinition->Count()) != 0 OR @(XamlPage->Count()) != 0 OR @(XamlAppDef->Count()) != 0"
			Include="$([MSBuild]::Escape('$(MSBuildProjectDirectory)\$(MSBuildProjectName)*_wpftmp$(MSBuildProjectExtension)'))"/>
	</ItemGroup>

	<!--
		Properties for extension of 'ProjectReferenceTargets'.
		Append any current value which may have been provided in a 'Directory.Build.targets' since the intent was likely to append, not prepend.
	-->
	<PropertyGroup Condition="'$(IsGraphBuild)' == 'true'">
		<!-- Empty case is for outer builds which do not import the target files that set 'BuildProjectReferences' -->
		<_MainReferenceTarget Condition="'$(BuildProjectReferences)' == '' OR '$(BuildProjectReferences)' == 'true'">.projectReferenceTargetsOrDefaultTargets</_MainReferenceTarget>
		<_MainReferenceTarget Condition="'$(_MainReferenceTarget)' == ''">GetTargetPath</_MainReferenceTarget>

		<ProjectReferenceTargetsForBuildInOuterBuild>GetTargetFrameworks;$(ProjectReferenceTargetsForBuildInOuterBuild)</ProjectReferenceTargetsForBuildInOuterBuild>
		<ProjectReferenceTargetsForBuild>$(_MainReferenceTarget);GetNativeManifest;$(_RecursiveTargetForContentCopying);GetTargetFrameworksWithPlatformForSingleTargetFramework;$(ProjectReferenceTargetsForBuild)</ProjectReferenceTargetsForBuild>

		<ProjectReferenceTargetsForCleanInOuterBuild>GetTargetFrameworks;$(ProjectReferenceTargetsForCleanInOuterBuild)</ProjectReferenceTargetsForCleanInOuterBuild>
		<ProjectReferenceTargetsForClean>Clean;GetTargetFrameworksWithPlatformForSingleTargetFramework;$(ProjectReferenceTargetsForClean)</ProjectReferenceTargetsForClean>

		<ProjectReferenceTargetsForRebuildInOuterBuild>$(ProjectReferenceTargetsForCleanInOuterBuild);$(ProjectReferenceTargetsForBuildInOuterBuild);$(ProjectReferenceTargetsForRebuildInOuterBuild)</ProjectReferenceTargetsForRebuildInOuterBuild>
		<ProjectReferenceTargetsForRebuild>$(ProjectReferenceTargetsForClean);$(ProjectReferenceTargetsForBuild);$(ProjectReferenceTargetsForRebuild)</ProjectReferenceTargetsForRebuild>

		<ProjectReferenceTargetsForPublishInOuterBuild>GetTargetFrameworks;$(ProjectReferenceTargetsForPublishInOuterBuild)</ProjectReferenceTargetsForPublishInOuterBuild>
		<ProjectReferenceTargetsForPublish>GetCopyToPublishDirectoryItems;$(ProjectReferenceTargetsForPublish)</ProjectReferenceTargetsForPublish>

		<ProjectReferenceTargetsForGetCopyToPublishDirectoryItems>GetCopyToPublishDirectoryItems;$(ProjectReferenceTargetsForGetCopyToPublishDirectoryItems)</ProjectReferenceTargetsForGetCopyToPublishDirectoryItems>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsGraphBuild)' == 'true'">
		<ProjectReferenceTargets Include="Build" Targets="$(ProjectReferenceTargetsForBuildInOuterBuild)" Condition="'$(ProjectReferenceTargetsForBuildInOuterBuild)' != ''" OuterBuild="true"/>
		<ProjectReferenceTargets Include="Build" Targets="$(ProjectReferenceTargetsForBuild)" Condition="'$(ProjectReferenceTargetsForBuild)' != ''"/>

		<ProjectReferenceTargets Include="Clean" Targets="$(ProjectReferenceTargetsForCleanInOuterBuild)" Condition="'$(ProjectReferenceTargetsForCleanInOuterBuild)' != ''" OuterBuild="true"/>
		<ProjectReferenceTargets Include="Clean" Targets="$(ProjectReferenceTargetsForClean)" Condition="'$(ProjectReferenceTargetsForClean)' != ''"/>

		<ProjectReferenceTargets Include="Rebuild" Targets="$(ProjectReferenceTargetsForRebuildInOuterBuild)" Condition="'$(ProjectReferenceTargetsForRebuildInOuterBuild)' != ''" OuterBuild="true"/>
		<ProjectReferenceTargets Include="Rebuild" Targets="$(ProjectReferenceTargetsForRebuild)" Condition="'$(ProjectReferenceTargetsForRebuild)' != ''"/>

		<ProjectReferenceTargets Include="Publish" Targets="$(ProjectReferenceTargetsForPublishInOuterBuild)" Condition="'$(ProjectReferenceTargetsForPublishInOuterBuild)' != ''" OuterBuild="true"/>
		<ProjectReferenceTargets Include="Publish" Targets="$(ProjectReferenceTargetsForPublish)" Condition="'$(ProjectReferenceTargetsForPublish)' != ''"/>

		<ProjectReferenceTargets Include="GetCopyToPublishDirectoryItems" Targets="$(ProjectReferenceTargetsForGetCopyToPublishDirectoryItems)" Condition="'$(ProjectReferenceTargetsForGetCopyToPublishDirectoryItems)' != ''"/>
	</ItemGroup>

	<!--
		Target that allows targets consuming source control confirmation to establish a dependency on targets producing this information.

		Any target that reads SourceRevisionId, PrivateRepositoryUrl, SourceRoot, and other source control properties and items
		should depend on this target and be conditioned on '$(SourceControlInformationFeatureSupported)' == 'true'.

		SourceRevisionId property uniquely identifies the source control revision of the repository the project belongs to.
		For Git repositories this id is a commit hash, for TFVC repositories it's the changeset number, etc.

		PrivateRepositoryUrl property stores the URL of the repository supplied by the CI server or retrieved from source control manager.
		Targets consuming this property shall not publish its value implicitly as it might inadvertently reveal an internal URL.
		Instead, they shall only do so if the project sets PublishRepositoryUrl property to true. For example, the NuGet Pack target
		may include the repository URL in the nuspec file generated for NuGet package produced by the project if PublishRepositoryUrl is true.

		SourceRoot item group lists all source roots that the project source files reside under and their mapping to source control server URLs,
		if available. This includes both source files under source control as well as source files in source packages. SourceRoot items are
		used by compilers to determine path map in deterministic build and by SourceLink provider, which maps local paths to URLs of source files
		stored on the source control server.

		Source control information provider that sets these properties and items shall execute before this target (by including
		InitializeSourceControlInformation in its BeforeTargets) and set source control properties and items that haven't been initialized yet.
	-->
	<Target Name="InitializeSourceControlInformation"/>

	<PropertyGroup>
		<SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
	</PropertyGroup>

</Project>